// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaign_recipients.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingRecipients = `-- name: CountPendingRecipients :one
SELECT count(*) FROM campaign_recipients WHERE campaign_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingRecipients(ctx context.Context, campaignID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingRecipients, campaignID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecipientsByStatus = `-- name: CountRecipientsByStatus :many
SELECT status, count(*) AS total
FROM campaign_recipients
WHERE campaign_id = $1
GROUP BY status
`

type CountRecipientsByStatusRow struct {
	Status RecipientStatus `json:"status"`
	Total  int64           `json:"total"`
}

func (q *Queries) CountRecipientsByStatus(ctx context.Context, campaignID pgtype.UUID) ([]CountRecipientsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countRecipientsByStatus, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountRecipientsByStatusRow
	for rows.Next() {
		var i CountRecipientsByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCampaignRecipient = `-- name: CreateCampaignRecipient :one
INSERT INTO campaign_recipients (campaign_id, contact_id, company_id)
VALUES ($1, $2, $3)
ON CONFLICT (campaign_id, contact_id) DO NOTHING
RETURNING id, campaign_id, contact_id, company_id, status, error_message, sent_at, created_at
`

type CreateCampaignRecipientParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	ContactID  pgtype.UUID `json:"contact_id"`
	CompanyID  pgtype.UUID `json:"company_id"`
}

func (q *Queries) CreateCampaignRecipient(ctx context.Context, arg CreateCampaignRecipientParams) (CampaignRecipient, error) {
	row := q.db.QueryRow(ctx, createCampaignRecipient, arg.CampaignID, arg.ContactID, arg.CompanyID)
	var i CampaignRecipient
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ContactID,
		&i.CompanyID,
		&i.Status,
		&i.ErrorMessage,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCampaignRecipientByID = `-- name: GetCampaignRecipientByID :one
SELECT id, campaign_id, contact_id, company_id, status, error_message, sent_at, created_at FROM campaign_recipients WHERE id = $1
`

func (q *Queries) GetCampaignRecipientByID(ctx context.Context, id pgtype.UUID) (CampaignRecipient, error) {
	row := q.db.QueryRow(ctx, getCampaignRecipientByID, id)
	var i CampaignRecipient
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ContactID,
		&i.CompanyID,
		&i.Status,
		&i.ErrorMessage,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCampaignRecipients = `-- name: ListCampaignRecipients :many
SELECT
    cr.id, cr.campaign_id, cr.contact_id, cr.company_id, cr.status,
    cr.error_message, cr.sent_at, cr.created_at,
    ct.email AS contact_email, ct.full_name AS contact_full_name,
    co.name AS company_name, co.ai_needs AS company_ai_needs
FROM campaign_recipients cr
JOIN contacts ct ON ct.id = cr.contact_id
JOIN companies co ON co.id = cr.company_id
WHERE cr.campaign_id = $1
ORDER BY cr.created_at ASC
`

type ListCampaignRecipientsRow struct {
	ID              pgtype.UUID        `json:"id"`
	CampaignID      pgtype.UUID        `json:"campaign_id"`
	ContactID       pgtype.UUID        `json:"contact_id"`
	CompanyID       pgtype.UUID        `json:"company_id"`
	Status          RecipientStatus    `json:"status"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	SentAt          pgtype.Timestamptz `json:"sent_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ContactEmail    string             `json:"contact_email"`
	ContactFullName pgtype.Text        `json:"contact_full_name"`
	CompanyName     string             `json:"company_name"`
	CompanyAiNeeds  []byte             `json:"company_ai_needs"`
}

func (q *Queries) ListCampaignRecipients(ctx context.Context, campaignID pgtype.UUID) ([]ListCampaignRecipientsRow, error) {
	rows, err := q.db.Query(ctx, listCampaignRecipients, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampaignRecipientsRow
	for rows.Next() {
		var i ListCampaignRecipientsRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ContactID,
			&i.CompanyID,
			&i.Status,
			&i.ErrorMessage,
			&i.SentAt,
			&i.CreatedAt,
			&i.ContactEmail,
			&i.ContactFullName,
			&i.CompanyName,
			&i.CompanyAiNeeds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRecipients = `-- name: ListPendingRecipients :many
SELECT
    cr.id, cr.campaign_id, cr.contact_id, cr.company_id, cr.status,
    cr.error_message, cr.sent_at, cr.created_at,
    ct.email AS contact_email, ct.full_name AS contact_full_name,
    co.name AS company_name, co.ai_needs AS company_ai_needs
FROM campaign_recipients cr
JOIN contacts ct ON ct.id = cr.contact_id
JOIN companies co ON co.id = cr.company_id
WHERE cr.campaign_id = $1 AND cr.status = 'pending'
ORDER BY cr.created_at ASC
`

type ListPendingRecipientsRow struct {
	ID              pgtype.UUID        `json:"id"`
	CampaignID      pgtype.UUID        `json:"campaign_id"`
	ContactID       pgtype.UUID        `json:"contact_id"`
	CompanyID       pgtype.UUID        `json:"company_id"`
	Status          RecipientStatus    `json:"status"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	SentAt          pgtype.Timestamptz `json:"sent_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ContactEmail    string             `json:"contact_email"`
	ContactFullName pgtype.Text        `json:"contact_full_name"`
	CompanyName     string             `json:"company_name"`
	CompanyAiNeeds  []byte             `json:"company_ai_needs"`
}

func (q *Queries) ListPendingRecipients(ctx context.Context, campaignID pgtype.UUID) ([]ListPendingRecipientsRow, error) {
	rows, err := q.db.Query(ctx, listPendingRecipients, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingRecipientsRow
	for rows.Next() {
		var i ListPendingRecipientsRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ContactID,
			&i.CompanyID,
			&i.Status,
			&i.ErrorMessage,
			&i.SentAt,
			&i.CreatedAt,
			&i.ContactEmail,
			&i.ContactFullName,
			&i.CompanyName,
			&i.CompanyAiNeeds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecipientFailed = `-- name: MarkRecipientFailed :exec
UPDATE campaign_recipients SET status = 'failed', error_message = $2 WHERE id = $1
`

type MarkRecipientFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkRecipientFailed(ctx context.Context, arg MarkRecipientFailedParams) error {
	_, err := q.db.Exec(ctx, markRecipientFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markRecipientSent = `-- name: MarkRecipientSent :exec
UPDATE campaign_recipients SET status = 'sent', sent_at = now() WHERE id = $1
`

func (q *Queries) MarkRecipientSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markRecipientSent, id)
	return err
}

const markRecipientUnsubscribed = `-- name: MarkRecipientUnsubscribed :exec
UPDATE campaign_recipients SET status = 'unsubscribed' WHERE id = $1
`

func (q *Queries) MarkRecipientUnsubscribed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markRecipientUnsubscribed, id)
	return err
}
