// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaigns.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSentToday = `-- name: CountSentToday :one
SELECT count(*)
FROM campaign_recipients cr
JOIN campaigns c ON c.id = cr.campaign_id
WHERE c.user_id = $1
  AND cr.status = 'sent'
  AND cr.sent_at >= date_trunc('day', now())
`

func (q *Queries) CountSentToday(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSentToday, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (user_id, name, subject, body)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, subject, body, status, created_at, updated_at, sent_at
`

type CreateCampaignParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Name    string      `json:"name"`
	Subject string      `json:"subject"`
	Body    string      `json:"body"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.UserID,
		arg.Name,
		arg.Subject,
		arg.Body,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :exec
DELETE FROM campaigns WHERE id = $1
`

func (q *Queries) DeleteCampaign(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCampaign, id)
	return err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, user_id, name, subject, body, status, created_at, updated_at, sent_at FROM campaigns WHERE id = $1
`

func (q *Queries) GetCampaignByID(ctx context.Context, id pgtype.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByID, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}

const listCampaignsByUser = `-- name: ListCampaignsByUser :many
SELECT id, user_id, name, subject, body, status, created_at, updated_at, sent_at FROM campaigns WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListCampaignsByUser(ctx context.Context, userID pgtype.UUID) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Subject,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCampaignSent = `-- name: MarkCampaignSent :one
UPDATE campaigns SET status = 'sent', sent_at = now(), updated_at = now() WHERE id = $1 RETURNING id, user_id, name, subject, body, status, created_at, updated_at, sent_at
`

func (q *Queries) MarkCampaignSent(ctx context.Context, id pgtype.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, markCampaignSent, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}

const setCampaignStatus = `-- name: SetCampaignStatus :one
UPDATE campaigns SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, user_id, name, subject, body, status, created_at, updated_at, sent_at
`

type SetCampaignStatusParams struct {
	ID     pgtype.UUID    `json:"id"`
	Status CampaignStatus `json:"status"`
}

func (q *Queries) SetCampaignStatus(ctx context.Context, arg SetCampaignStatusParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, setCampaignStatus, arg.ID, arg.Status)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}
