// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCompaniesByUser = `-- name: CountCompaniesByUser :one
SELECT count(*) FROM companies WHERE user_id = $1
`

func (q *Queries) CountCompaniesByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompaniesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (user_id, name, domain, website_url, address, phone, email, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, name, domain, website_url, status, notes, created_at, updated_at, trustpilot_rating, trustpilot_review_count, trustpilot_fetched_at, ai_needs, ai_summary, ai_analyzed_at, address, phone, email
`

type CreateCompanyParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Name       string      `json:"name"`
	Domain     pgtype.Text `json:"domain"`
	WebsiteUrl pgtype.Text `json:"website_url"`
	Address    pgtype.Text `json:"address"`
	Phone      pgtype.Text `json:"phone"`
	Email      pgtype.Text `json:"email"`
	Notes      pgtype.Text `json:"notes"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.UserID,
		arg.Name,
		arg.Domain,
		arg.WebsiteUrl,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.Notes,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Domain,
		&i.WebsiteUrl,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrustpilotRating,
		&i.TrustpilotReviewCount,
		&i.TrustpilotFetchedAt,
		&i.AiNeeds,
		&i.AiSummary,
		&i.AiAnalyzedAt,
		&i.Address,
		&i.Phone,
		&i.Email,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :exec
DELETE FROM companies WHERE id = $1
`

func (q *Queries) DeleteCompany(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCompany, id)
	return err
}

const getCompanyByID = `-- name: GetCompanyByID :one
SELECT id, user_id, name, domain, website_url, status, notes, created_at, updated_at, trustpilot_rating, trustpilot_review_count, trustpilot_fetched_at, ai_needs, ai_summary, ai_analyzed_at, address, phone, email FROM companies WHERE id = $1
`

func (q *Queries) GetCompanyByID(ctx context.Context, id pgtype.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByID, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Domain,
		&i.WebsiteUrl,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrustpilotRating,
		&i.TrustpilotReviewCount,
		&i.TrustpilotFetchedAt,
		&i.AiNeeds,
		&i.AiSummary,
		&i.AiAnalyzedAt,
		&i.Address,
		&i.Phone,
		&i.Email,
	)
	return i, err
}

const listCompaniesByUser = `-- name: ListCompaniesByUser :many
SELECT id, user_id, name, domain, website_url, status, notes, created_at, updated_at, trustpilot_rating, trustpilot_review_count, trustpilot_fetched_at, ai_needs, ai_summary, ai_analyzed_at, address, phone, email FROM companies
WHERE user_id = $1
  AND ($2::company_status IS NULL OR status = $2)
  AND (
    $3::text IS NULL
    OR name ILIKE '%' || $3::text || '%'
    OR domain ILIKE '%' || $3::text || '%'
  )
ORDER BY created_at DESC
`

type ListCompaniesByUserParams struct {
	UserID pgtype.UUID       `json:"user_id"`
	Status NullCompanyStatus `json:"status"`
	Search pgtype.Text       `json:"search"`
}

func (q *Queries) ListCompaniesByUser(ctx context.Context, arg ListCompaniesByUserParams) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompaniesByUser, arg.UserID, arg.Status, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Domain,
			&i.WebsiteUrl,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrustpilotRating,
			&i.TrustpilotReviewCount,
			&i.TrustpilotFetchedAt,
			&i.AiNeeds,
			&i.AiSummary,
			&i.AiAnalyzedAt,
			&i.Address,
			&i.Phone,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies
SET
    name = coalesce($1, name),
    domain = coalesce($2, domain),
    website_url = coalesce($3, website_url),
    address = coalesce($4, address),
    phone = coalesce($5, phone),
    email = coalesce($6, email),
    status = coalesce($7, status),
    notes = coalesce($8, notes),
    updated_at = now()
WHERE id = $9
RETURNING id, user_id, name, domain, website_url, status, notes, created_at, updated_at, trustpilot_rating, trustpilot_review_count, trustpilot_fetched_at, ai_needs, ai_summary, ai_analyzed_at, address, phone, email
`

type UpdateCompanyParams struct {
	Name       pgtype.Text       `json:"name"`
	Domain     pgtype.Text       `json:"domain"`
	WebsiteUrl pgtype.Text       `json:"website_url"`
	Address    pgtype.Text       `json:"address"`
	Phone      pgtype.Text       `json:"phone"`
	Email      pgtype.Text       `json:"email"`
	Status     NullCompanyStatus `json:"status"`
	Notes      pgtype.Text       `json:"notes"`
	ID         pgtype.UUID       `json:"id"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.Name,
		arg.Domain,
		arg.WebsiteUrl,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.Status,
		arg.Notes,
		arg.ID,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Domain,
		&i.WebsiteUrl,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrustpilotRating,
		&i.TrustpilotReviewCount,
		&i.TrustpilotFetchedAt,
		&i.AiNeeds,
		&i.AiSummary,
		&i.AiAnalyzedAt,
		&i.Address,
		&i.Phone,
		&i.Email,
	)
	return i, err
}

const updateEnrichment = `-- name: UpdateEnrichment :one
UPDATE companies
SET
    trustpilot_rating = $1,
    trustpilot_review_count = $2,
    trustpilot_fetched_at = $3,
    ai_needs = $4,
    ai_summary = $5,
    ai_analyzed_at = $6,
    updated_at = now()
WHERE id = $7
RETURNING id, user_id, name, domain, website_url, status, notes, created_at, updated_at, trustpilot_rating, trustpilot_review_count, trustpilot_fetched_at, ai_needs, ai_summary, ai_analyzed_at, address, phone, email
`

type UpdateEnrichmentParams struct {
	TrustpilotRating      pgtype.Float4      `json:"trustpilot_rating"`
	TrustpilotReviewCount pgtype.Int4        `json:"trustpilot_review_count"`
	TrustpilotFetchedAt   pgtype.Timestamptz `json:"trustpilot_fetched_at"`
	AiNeeds               []byte             `json:"ai_needs"`
	AiSummary             pgtype.Text        `json:"ai_summary"`
	AiAnalyzedAt          pgtype.Timestamptz `json:"ai_analyzed_at"`
	ID                    pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateEnrichment(ctx context.Context, arg UpdateEnrichmentParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateEnrichment,
		arg.TrustpilotRating,
		arg.TrustpilotReviewCount,
		arg.TrustpilotFetchedAt,
		arg.AiNeeds,
		arg.AiSummary,
		arg.AiAnalyzedAt,
		arg.ID,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Domain,
		&i.WebsiteUrl,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrustpilotRating,
		&i.TrustpilotReviewCount,
		&i.TrustpilotFetchedAt,
		&i.AiNeeds,
		&i.AiSummary,
		&i.AiAnalyzedAt,
		&i.Address,
		&i.Phone,
		&i.Email,
	)
	return i, err
}
