// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (company_id, email, full_name, source_note)
VALUES ($1, $2, $3, $4)
RETURNING id, company_id, email, full_name, source_note, created_at
`

type CreateContactParams struct {
	CompanyID  pgtype.UUID `json:"company_id"`
	Email      string      `json:"email"`
	FullName   pgtype.Text `json:"full_name"`
	SourceNote string      `json:"source_note"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.CompanyID,
		arg.Email,
		arg.FullName,
		arg.SourceNote,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.FullName,
		&i.SourceNote,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM contacts WHERE id = $1
`

func (q *Queries) DeleteContact(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteContact, id)
	return err
}

const getContactByID = `-- name: GetContactByID :one
SELECT id, company_id, email, full_name, source_note, created_at FROM contacts WHERE id = $1
`

func (q *Queries) GetContactByID(ctx context.Context, id pgtype.UUID) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactByID, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.FullName,
		&i.SourceNote,
		&i.CreatedAt,
	)
	return i, err
}

const listContactsByCompany = `-- name: ListContactsByCompany :many
SELECT id, company_id, email, full_name, source_note, created_at FROM contacts WHERE company_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListContactsByCompany(ctx context.Context, companyID pgtype.UUID) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContactsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Email,
			&i.FullName,
			&i.SourceNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
