// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CompanyStatus string

const (
	CompanyStatusNew       CompanyStatus = "new"
	CompanyStatusContacted CompanyStatus = "contacted"
	CompanyStatusReplied   CompanyStatus = "replied"
	CompanyStatusConverted CompanyStatus = "converted"
	CompanyStatusLost      CompanyStatus = "lost"
)

func (e *CompanyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompanyStatus(s)
	case string:
		*e = CompanyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CompanyStatus: %T", src)
	}
	return nil
}

type NullCompanyStatus struct {
	CompanyStatus CompanyStatus `json:"company_status"`
	Valid         bool          `json:"valid"` // Valid is true if CompanyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompanyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CompanyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompanyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompanyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompanyStatus), nil
}

type UserRole string

const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Company struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Name       string             `json:"name"`
	Domain     pgtype.Text        `json:"domain"`
	WebsiteUrl pgtype.Text        `json:"website_url"`
	Status     CompanyStatus      `json:"status"`
	Notes      pgtype.Text        `json:"notes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Contact struct {
	ID         pgtype.UUID        `json:"id"`
	CompanyID  pgtype.UUID        `json:"company_id"`
	Email      string             `json:"email"`
	FullName   pgtype.Text        `json:"full_name"`
	SourceNote string             `json:"source_note"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         UserRole           `json:"role"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
