// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO email_templates (user_id, name, subject, body)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, subject, body, created_at, updated_at
`

type CreateTemplateParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Name    string      `json:"name"`
	Subject string      `json:"subject"`
	Body    string      `json:"body"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (EmailTemplate, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.UserID,
		arg.Name,
		arg.Subject,
		arg.Body,
	)
	var i EmailTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Subject,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM email_templates WHERE id = $1
`

func (q *Queries) DeleteTemplate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTemplate, id)
	return err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT id, user_id, name, subject, body, created_at, updated_at FROM email_templates WHERE id = $1
`

func (q *Queries) GetTemplateByID(ctx context.Context, id pgtype.UUID) (EmailTemplate, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, id)
	var i EmailTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Subject,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTemplatesByUser = `-- name: ListTemplatesByUser :many
SELECT id, user_id, name, subject, body, created_at, updated_at FROM email_templates WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTemplatesByUser(ctx context.Context, userID pgtype.UUID) ([]EmailTemplate, error) {
	rows, err := q.db.Query(ctx, listTemplatesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailTemplate
	for rows.Next() {
		var i EmailTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Subject,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE email_templates
SET
    name = coalesce($1, name),
    subject = coalesce($2, subject),
    body = coalesce($3, body),
    updated_at = now()
WHERE id = $4
RETURNING id, user_id, name, subject, body, created_at, updated_at
`

type UpdateTemplateParams struct {
	Name    pgtype.Text `json:"name"`
	Subject pgtype.Text `json:"subject"`
	Body    pgtype.Text `json:"body"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (EmailTemplate, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.Name,
		arg.Subject,
		arg.Body,
		arg.ID,
	)
	var i EmailTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Subject,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
