// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: unsubscribes.sql

package sqlc

import (
	"context"
)

const createUnsubscribe = `-- name: CreateUnsubscribe :exec
INSERT INTO unsubscribes (email) VALUES ($1) ON CONFLICT (email) DO NOTHING
`

func (q *Queries) CreateUnsubscribe(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, createUnsubscribe, email)
	return err
}

const isUnsubscribed = `-- name: IsUnsubscribed :one
SELECT EXISTS(SELECT 1 FROM unsubscribes WHERE email = $1)
`

func (q *Queries) IsUnsubscribed(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, isUnsubscribed, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
